CONTROLS = [
    {'id': 'AWS-GR_EBS_SNAPSHOT_PUBLIC_RESTORABLE_CHECK', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_ENCRYPTED_VOLUMES', 'include': ['All'], 'exclude': ''},
    {'id': 'AWS-GR_NO_UNRESTRICTED_ROUTE_TO_IGW', 'include': ['ALL'], 'exclude': ['Sandbox', 'Infrastructure']},
    {'id': 'AWS-GR_RESTRICTED_COMMON_PORTS', 'include': ['ALL'], 'exclude': ['Sandbox', 'Infrastructure']},
    {'id': 'AWS-GR_RESTRICTED_SSH', 'include': ['ALL'], 'exclude': ''},
    {'id': 'UBCGKOORFCMO', 'include': ['ALL'], 'exclude': ''},
    {'id': 'TPTBSUKLVYNV', 'include': ['ALL'], 'exclude': ''},
    {'id': 'HBOYAMQJYZKC', 'include': ['ALL'], 'exclude': ''},
    {'id': 'SQHQBAAOKFRN', 'include': ['ALL'], 'exclude': ''},
    {'id': 'EKEHTOJRBETQ', 'include': ['ALL'], 'exclude': ''},
    {'id': 'UFGUBZPYBLPN', 'include': ['ALL'], 'exclude': ''},
    {'id': 'EYLAVXIWUYJG', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_CLOUDWATCH_EVENTS_CHANGE_PROHIBITED', 'include': ['ALL'], 'exclude': ''},
    {'id': 'KEFOAQPLEGGA', 'include': ['ALL'], 'exclude': ''},
    {'id': 'JKDFTFHBBSEK', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_LAMBDA_CHANGE_PROHIBITED', 'include': ['ALL'], 'exclude': ''},
    {'id': 'PIGMDBBNREIU', 'include': ['ALL'], 'exclude': ''},
    {'id': 'JADBMJXDJEUI', 'include': ['ALL'], 'exclude': ''},
    {'id': 'YIKIWDHYLGBP', 'include': ['ALL'], 'exclude': ''},
    {'id': 'KPKAHTFYDJQQ', 'include': ['ALL'], 'exclude': ''},
    {'id': 'VLQZELIVKMED', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_RESTRICT_ROOT_USER', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_RESTRICT_ROOT_USER_ACCESS_KEYS', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_IAM_ROLE_CHANGE_PROHIBITED', 'include': ['ALL'], 'exclude': ''},
    {'id': 'OTDQBWDVYVJE', 'include': ['ALL'], 'exclude': ''},
    {'id': 'ASYFZUOMHFUQ', 'include': ['ALL'], 'exclude': ''},
    {'id': 'WUGDSPITURNA', 'include': ['ALL'], 'exclude': ''},
    {'id': 'LSUJTPCOEECR', 'include': ['ALL'], 'exclude': ''},
    {'id': 'WYRBYRJBCFGJ', 'include': ['ALL'], 'exclude': ''},
    {'id': 'OCMEJBXKCWSF', 'include': ['ALL'], 'exclude': ''},
    {'id': 'RNRFWUNSMVZO', 'include': ['ALL'], 'exclude': ''},
    {'id': 'DUWNOGUJJEYE', 'include': ['ALL'], 'exclude': ''},
    {'id': 'BSUTLBPTXDCX', 'include': ['ALL'], 'exclude': ''},
    {'id': 'BPQXZTSPWVVX', 'include': ['ALL'], 'exclude': ''},
    {'id': 'XMWBZXRYGTMC', 'include': ['ALL'], 'exclude': ''},
    {'id': 'SYIHFFPXEMOL', 'include': ['ALL'], 'exclude': ''},
    {'id': 'ZSWMQFPPNNOS', 'include': ['ALL'], 'exclude': ''},
    {'id': 'PNVPPZDHTLDX', 'include': ['ALL'], 'exclude': ''},
    {'id': 'OHTOUHWXBHVL', 'include': ['ALL'], 'exclude': ''},
    {'id': 'UWGSZEDUWTBP', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_CLOUDTRAIL_CHANGE_PROHIBITED', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_CONFIG_AGGREGATION_AUTHORIZATION_POLICY', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_CONFIG_AGGREGATION_CHANGE_PROHIBITED', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_CONFIG_CHANGE_PROHIBITED', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_CONFIG_RULE_CHANGE_PROHIBITED', 'include': ['ALL'], 'exclude': ''},
    {'id': 'AWS-GR_ROOT_ACCOUNT_MFA_ENABLED', 'include': ['ALL'], 'exclude': ''},
    {'id': 'GPMRUNIPAAHZ', 'include': ['ALL'], 'exclude': ''},
    {'id': 'JGYSATNSTORL', 'include': ['ALL'], 'exclude': ''},
    {'id': 'PQTGHIEDIOPD', 'include': ['ALL'], 'exclude': ''},
]

